/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_appsync_graphqlEndpoint:
    'https://m3bualugrvaxvhvhzqbmecdjyi.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-west-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_appsync_apiKey: 'da2-i5kv4rmunrgltjxzw6y526kl7e',
  aws_user_files_s3_bucket: 'change-agent-s3-adm-master',
  aws_user_files_s3_bucket_region: 'eu-west-1',
  aws_dynamodb_all_tables_region: 'eu-west-1',
  aws_dynamodb_table_schemas: [
    {
      tableName: 'PhoneNumber-master',
      region: 'eu-west-1',
    },
  ],
  aws_cognito_identity_pool_id: 'eu-west-1:5aace98b-78d8-4ef9-9b02-abd233898b7f',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_4x5EBX2PF',
  aws_user_pools_web_client_id: '1b3o4kis62t2tgnachtkpl8gjt',
  oauth: {},
};

export default awsmobile;
